; Do not report issues using a configuration other than the default

[capture]
; A buffer used to estimate a game's framerate by averaging the delta time between captured frames [1-]
; This value greatly affects both framepacing and stability
frametime_buffer_size = 15

[lsfg]
; How often to run UI detection, in base frames [0-4]
; lsfg2:
; 1 - Better quality, 4 - Better performance, 0 - UI detection off
; lsfg3:
; 1 - UI detection on, 0 - UI detection off
ui_detection_rate = 1

[fps_counter]
scale = 1.0
color = 0xD3D3D3